### ISSUE TITLE
Sporadic exceptions when target process log messages

### ISSUE THREAD

**Issue by guillaumecottinet-eaton** [NLog/NLog.WCF#5]
We started to see sporadic exceptions in our applications since we moved from NLog 4 to NLog 5
```
System.ArgumentOutOfRangeException
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(System.ExceptionArgument, System.ExceptionResource)
   at System.Collections.Generic.List`1[[NLog.Common.AsyncLogEventInfo, NLog, Version=5.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c]].get_Item(Int32)
   at NLog.Targets.LogReceiverWebServiceTarget+<>c__DisplayClass39_0.<Send>b__0(System.Object, System.ComponentModel.AsyncCompletedEventArgs)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at NLog.LogReceiverService.WcfLogReceiverClientBase`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].OnProcessLogMessagesCompleted(System.Object)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

```
System.NullReferenceException
   at NLog.Targets.LogReceiverWebServiceTarget+<>c__DisplayClass39_0.<Send>b__0(System.Object, System.ComponentModel.AsyncCompletedEventArgs)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at NLog.LogReceiverService.WcfLogReceiverClientBase`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].OnProcessLogMessagesCompleted(System.Object)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

### Reproduction
We were not able to create a simple example that reproduce the issue. We also do not have a specific sequence within our applications to reproduce it. Looping within our code so there is thousands of log generated every minute, we've been able to see the issue really fast (within few seconds) or after few hours. It feels like a timing issue versus async usage.

### Configuration
Our applications all use the same NLog configuration. Targets are async
`<targets async="true">`
We are using 3 file targets, 2 WCF and one home made. Wcf targets configuration looks like
```
<target Type="LogReceiverService" name="Wcf" endpointConfigurationName="NLogService" endpointAddress="net.pipe://localhost/${xxxxxxxxxxx}"
        useBinaryEncoding="True" includeEventProperties="True" UseOneWayContract="True">
  <parameter name="date" type="System.String" layout="${longdate}"/>
  <parameter name="level" type="System.String" layout="${uppercase:${level}}"/>
  <parameter name="source" type="System.String" layout="${logger}"/>
  <parameter name="message" type="System.String" layout="${message}"/>
</target>
```

**Comment by snakefoot** [comment]
Again thank for reporting this bug. It will hopefully save others from a bad time.
